/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { AccessSecretRegistry } from "./AccessSecretRegistry";

export class AccessSecretRegistry {
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): AccessSecretRegistry {
        return new Contract(address, _abi, signerOrProvider) as AccessSecretRegistry;
    }
}