/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface BooleanOutcomeInterface extends Interface {
    functions: {
        isFinalized: TypedFunctionDescription<{
            encode([_query]: [Arrayish]): string;
        }>;

        getOutcome: TypedFunctionDescription<{
            encode([_query]: [Arrayish]): string;
        }>;
    };
}

